### PR TITLE
Event dispatched along with retailer data when set.

### PR DESCRIPTION
**Pull request by Chacalbis**
This event will be used to save customer's favorite retailers.

### CODE REVIEW

**Comment by TheGuit** [comment]
@romainruaud @afoucret pouvez-vous regardez cette pull-request et nous faire un retour ?

Cordialement,

**Comment by delyriand** [comment]
Hi @Chacalbis and @TheGuit,

I have 2 problems with this PR:
- indentation and spacing (the end parenthesis and the semicolon of the dispatch method should be at a new line, missing spacing around assignment operator in array)
- why not put a after plugin on setRetailer method?

**Comment by Chacalbis** [comment]
Hi @delyriand,

Indeed, defining a plugin with an after method sounds like a better alternative. I guess such customizations should be done using plugins for public methods like setRetailer whenever possible.
We just didn't give it a thought at the time. 

We can either drop this PR and make the appropriate changes in our code.
Or we can fix these indentation and spacing issues.

Thank you for your feedback

**Comment by delyriand** [comment]
Hello @Chacalbis,

if you can modify your code instead of an observer, i prefer this solution.

I closed the PR but do not hesitate to contribute again ;)

**Pull request closed without merging**
